### ISSUE TITLE
The tool is touching the file again after updating it's timestamps

### ISSUE THREAD

**Issue by PBreezy** [limbenjamin/nTimetools#1]
I'm trying to test nTimestomp in windows 10 and the tool is touching the file again roughly 5 seconds after i run it. Initially all 4 timestamps are set to the given value but the access value always updates shortly after. 

Here's my syntax and i'm trying to alter text files.

nTimestomp.exe C:\users\me\documents\test.txt “2019-03-01 11:11:11.12345678” “2019-03-01 11:11:11.12345678” “2019-03-01 11:11:11.12345678” “2019-03-01 11:11:11.12345678”

**Comment by limbenjamin** [comment]
How did u view the access timestamp value? If you use right click -> properties, it will cause the access timestamp to be updated.

Try using nTimeview.exe C:\users\me\documents\test.txt or other tools to check the timestamp.

**Comment by PBreezy** [comment]
I used ntimeview and got the same results as well as imaging the drive parsing the MFT. I also tried turning off all the antivirus and it still happened. I have a suspicion that might be the version of Windows 10 I’m using because I tried on a Windows 7 VM and it was all good. Have you tested it on Windows 10? I’m on 1803

**Comment by limbenjamin** [comment]
Yep, I have it working on Win 10 Build 17134. There is a registry key that will affect file access timestamps. Might be worthwhile to fiddle with it.

https://forums.guru3d.com/threads/ntfs-disable-last-access-update-file-time-stamp-windows-10-april-1803-update.421228/

Mine is set to 0x80000002, I can get it to work.

**Comment by PBreezy** [comment]
Nice that worked well, set mine to 2 as well and everything is good. Thanks
for the help and great tools!
