### ISSUE TITLE
timestomping works on $SI only or $SI and $FN time attributes ?

### ISSUE THREAD

**Issue by Sim4n6** [limbenjamin/nTimetools#2]
I just want to be sure about one thing please.

When I use ntimestomp does it update $STANDARD_INFORMATION timestamps attributes only or both $FILE_NAME timestamps attributes and $SI, please ?

**Comment by limbenjamin** [comment]
$STANDARD_INFORMATION only

**Comment by Sim4n6** [comment]
Thanks
