### ISSUE TITLE
nTimestomp allows to change certain timestamps

### ISSUE THREAD

**Issue by ghost** [limbenjamin/nTimetools#4]
I have not found a way to change certain timestamps in nTimestomp version 1.1.

The idea is to make something like this possible and it should look like this.

Parameter:
`-M` = Last Write Time
`-A` = Last Access Time
`-C` = Metadata Change Time
`-B` = Creation Time

Additional Parameter (here the timestamps are changed to the same time):
`-MA` = Last Write Time and Last Access Time
`-MC` = Last Write Time and Metadata Change Time
`-MB` = Last Write Time and Creation Time
`-MAC` = Last Write Time, Last Access Time and Metadata Change Time
`-MACB` = Last Write Time, Last Access Time, Metadata Change Time and Creation Time

`-AC` = Last Access Time and Metadata Change Time
`-AB` = Last Access Time and Creation Time
`-ACB` = Last Access Time, Metadata Change Time and Creation Time

`-CB` = Metadata Change Time and Creation Time

**Comment by limbenjamin** [comment]
Hi filIAI,

I have addressed this in issue #3.

Closing this issue.
