### ISSUE TITLE
Allow with nTimestomp to set the date 60056-05-28

### ISSUE THREAD

**Issue by gitbbkload** [limbenjamin/nTimetools#5]
[Date range | 1  January 1601 – 28 May 60056 (File times are 64-bit numbers counting  100-nanosecond intervals (ten million per second) since 1601, which is  58,000+ years)](https://en.wikipedia.org/wiki/NTFS)

`nTimestomp_v1.2_x64.exe -F "C:\Users\flroida\Desktop\60056.txt" -M "60056-05-28 23:59:59.9999999" -A "60056-05-28 23:59:59.9999999" -C "60056-05-28 23:59:59.9999999" -B "60056-05-28 23:59:59.9999999"`

Result:
```
nTimestomp, Version 1.2
Copyright (C) 2019 Benjamin Lim
Available for free from https://limbenjamin.com/pages/ntimetools

mchgWrong Date Format
```

**Comment by limbenjamin** [comment]
Won't fix. No practical use for setting it to such a far off date.
