### ISSUE TITLE
Support directories/folders

### ISSUE THREAD

**Issue by tamarisklog** [limbenjamin/nTimetools#7]
I tried using nTimeview to get the directories/folder inforamtion, but it doesn't work.

There is no support for directories/folder.

**Comment by limbenjamin** [comment]
Whoever you are, please do some research on the topic and stop creating anonymous accounts leaving low quality issues on repositories. It does not help developers.

https://github.com/filIAI. 
- Account created Sep 5 2021
- Opened issue #3 and #4 on my nTimetools repository on Sep 10 2021.
- No other activity apart from opening similar low quality issues on other repositories.

https://github.com/gitbbkload
- Account created Sep 13 2021
- Opened issues #5 and #6 on my nTimetools repository on Sep 14 2021
- No other activity apart from opening similar low quality issues on other repositories.
- Commented on issue #3 which proves that he is the same person behind filIAI

https://github.com/tamarisklog
- Account created Sep 30 2021
- Opened issues #7 and #8 on my nTimetools repository on Sep 30 2021
- No other activity
