### ISSUE TITLE
Windows 11 updates Metadata Change Time when creating the file

### ISSUE THREAD

**Issue by tamarisklog** [limbenjamin/nTimetools#8]
I tried using nTimeview to get the file infomation, but it seems that with Windows 11 there are some changes when a file is created. [C] Metadata Change Time is updated.

Create a new .txt file by right mouse click (New -> Text Document).

Here is the output:

```
Filesystem type: NTFS
Filename: C:\Users\xxx\Desktop\New Text Document.txt
File size: 0

[M] Last Write Time:                                        2021-09-30 06:47:02.9250998 UTC
[A] Last Access Time:                                       2021-09-30 06:47:02.9250998 UTC
[C] Metadata Change Time:                                   **2021-09-30 06:47:03.6125600 UTC**
[B] Creation Time:                                          2021-09-30 06:47:02.9250998 UTC
```

Under Windows 10 (21H1) is also the same problem.

In Windows 7, 8 or Windows 8.1 it is not so, here is the correct behavior, that is when creating a new file all have the same timestamp as [B] Creation Time.

Is this a bug in Windows 11 and Windows 10 or has Microsoft added a new behavior? Can you reproduce the problem on your site as well?

**Comment by limbenjamin** [comment]
> Is this a bug in Windows 11 and Windows 10 or has Microsoft added a new behavior?

If you suspect there is a bug or new feature in Win10/11, maybe you should ask Microsoft instead of opening an issue here.
