### ISSUE TITLE
Timestomp of last access time

### ISSUE THREAD

**Issue by HennelovaZuzana** [limbenjamin/nTimetools#9]
I just tried to timestomp the last acces time and then used the Timeview tool to check it. Last access time seems to always change to the time when i used timestomp on the file.

**Comment by limbenjamin** [comment]
Hi, please check out issue #1 . A number of possible reasons is listed there.

**Comment by HennelovaZuzana** [comment]
Hi, thank you for the response and re-directing. So if I understand this right, I would probably need to disable Last Access Update File Time Stamp on Windows for this to work?
